# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/jcoffman/work/Cora-Z7-10-base-linux/src/constraints/Cora-Z7-10-Master.xdc

# Block Designs: /home/jcoffman/work/Cora-Z7-10-base-linux/src/bd/cora_z7_10/cora_z7_10.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cora_z7_10 || ORIG_REF_NAME==cora_z7_10} -quiet] -quiet

# IP: /home/jcoffman/work/Cora-Z7-10-base-linux/src/bd/cora_z7_10/ip/cora_z7_10_processing_system7_0_0/cora_z7_10_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cora_z7_10_processing_system7_0_0 || ORIG_REF_NAME==cora_z7_10_processing_system7_0_0} -quiet] -quiet

# IP: /home/jcoffman/work/Cora-Z7-10-base-linux/src/bd/cora_z7_10/ip/cora_z7_10_axi_gpio_0_0/cora_z7_10_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cora_z7_10_axi_gpio_0_0 || ORIG_REF_NAME==cora_z7_10_axi_gpio_0_0} -quiet] -quiet

# IP: /home/jcoffman/work/Cora-Z7-10-base-linux/src/bd/cora_z7_10/ip/cora_z7_10_axi_gpio_1_0/cora_z7_10_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cora_z7_10_axi_gpio_1_0 || ORIG_REF_NAME==cora_z7_10_axi_gpio_1_0} -quiet] -quiet

# IP: /home/jcoffman/work/Cora-Z7-10-base-linux/src/bd/cora_z7_10/ip/cora_z7_10_ps7_0_axi_periph_0/cora_z7_10_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cora_z7_10_ps7_0_axi_periph_0 || ORIG_REF_NAME==cora_z7_10_ps7_0_axi_periph_0} -quiet] -quiet

# IP: /home/jcoffman/work/Cora-Z7-10-base-linux/src/bd/cora_z7_10/ip/cora_z7_10_rst_ps7_0_100M_0/cora_z7_10_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cora_z7_10_rst_ps7_0_100M_0 || ORIG_REF_NAME==cora_z7_10_rst_ps7_0_100M_0} -quiet] -quiet

# IP: /home/jcoffman/work/Cora-Z7-10-base-linux/src/bd/cora_z7_10/ip/cora_z7_10_xlconcat_0_0/cora_z7_10_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cora_z7_10_xlconcat_0_0 || ORIG_REF_NAME==cora_z7_10_xlconcat_0_0} -quiet] -quiet

# IP: /home/jcoffman/work/Cora-Z7-10-base-linux/src/bd/cora_z7_10/ip/cora_z7_10_xbar_0/cora_z7_10_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cora_z7_10_xbar_0 || ORIG_REF_NAME==cora_z7_10_xbar_0} -quiet] -quiet

# IP: /home/jcoffman/work/Cora-Z7-10-base-linux/src/bd/cora_z7_10/ip/cora_z7_10_xlconcat_1_0/cora_z7_10_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cora_z7_10_xlconcat_1_0 || ORIG_REF_NAME==cora_z7_10_xlconcat_1_0} -quiet] -quiet

# IP: /home/jcoffman/work/Cora-Z7-10-base-linux/src/bd/cora_z7_10/ip/cora_z7_10_xadc_wiz_0_1/cora_z7_10_xadc_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cora_z7_10_xadc_wiz_0_1 || ORIG_REF_NAME==cora_z7_10_xadc_wiz_0_1} -quiet] -quiet

# IP: /home/jcoffman/work/Cora-Z7-10-base-linux/src/bd/cora_z7_10/ip/cora_z7_10_pwm_rgb_0/cora_z7_10_pwm_rgb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cora_z7_10_pwm_rgb_0 || ORIG_REF_NAME==cora_z7_10_pwm_rgb_0} -quiet] -quiet

# IP: /home/jcoffman/work/Cora-Z7-10-base-linux/src/bd/cora_z7_10/ip/cora_z7_10_auto_pc_0/cora_z7_10_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cora_z7_10_auto_pc_0 || ORIG_REF_NAME==cora_z7_10_auto_pc_0} -quiet] -quiet

# XDC: /home/jcoffman/work/Cora-Z7-10-base-linux/src/bd/cora_z7_10/cora_z7_10_ooc.xdc
